refactor!: Update SView parrsing to new slotted properties
ApptiveGrid/ApptiveGrid-flutter pull request #130
Opened 2023-11-06 22:50 UTC by soeren-schmaljohann-2denker

2023-11-07 08:34 UTC, ABausG commented
The goal for this is to be explicitly **not** a breaking change as we need to allow a phase where the app still supports both format.
The strategy should follow these steps:

- Keep the current constructor arguments but assign them to nullable private fields, mark them as deprecated and adjust the current variables to be getters that use the probate implementation of available or construct them through the new slot variant
- move some of the required keywords to be represented as assertions such that there is no breaking change but still a sort of safety for creating it

Also I remember that @bocasti mentioned that the data in principle is still the same so possibly we don't even need a new data type for the slots but can instead still use the old data? If that's the case we might even keep the current structure (maybe renaming some variables and deprecating old names) and only having to adjust the json constructors

2023-11-07 12:52 UTC, soeren-schmaljohann-2denker commented
@ABausG I refactored it to no longer be a breaking change

2023-11-07 13:40 UTC, bocasti commented
> The goal for this is to be explicitly **not** a breaking change as we need to allow a phase where the app still supports both format. The strategy should follow these steps:
> 
> * Keep the current constructor arguments but assign them to nullable private fields, mark them as deprecated and adjust the current variables to be getters that use the probate implementation of available or construct them through the new slot variant
> * move some of the required keywords to be represented as assertions such that there is no breaking change but still a sort of safety for creating it
> 
> Also I remember that @bocasti mentioned that the data in principle is still the same so possibly we don't even need a new data type for the slots but can instead still use the old data? If that's the case we might even keep the current structure (maybe renaming some variables and deprecating old names) and only having to adjust the json constructors



> The goal for this is to be explicitly **not** a breaking change as we need to allow a phase where the app still supports both format. The strategy should follow these steps:
> 
> * Keep the current constructor arguments but assign them to nullable private fields, mark them as deprecated and adjust the current variables to be getters that use the probate implementation of available or construct them through the new slot variant
> * move some of the required keywords to be represented as assertions such that there is no breaking change but still a sort of safety for creating it
> 
> Also I remember that @bocasti mentioned that the data in principle is still the same so possibly we don't even need a new data type for the slots but can instead still use the old data? If that's the case we might even keep the current structure (maybe renaming some variables and deprecating old names) and only having to adjust the json constructors

I confirm that only the json format of the view resource should change. It should be the same content (same keys and values) but presented differently

2023-11-07 15:01 UTC, ABausG requested changes
See the comment. The deprectation is not yet layed out for truly allowing compatibility with both ways.

I'm attaching some responses to the ticket with data in the old/new format that should be used for the tests

2023-11-08 08:47 UTC, ABausG commented
I just realised that we might want to just make the following:

- Adjust this to only add the slot properties and not touch the old things apart from marking them with deprectated
- DON'T release that version but instead build a version of the apptive launcher with a dependency override onto this git branch
- Do a breaking change once that is released with the changes more or less from the first Review.


Sorry for not coming up with that solution earlier. What do you think about that?

2023-11-08 13:37 UTC, soeren-schmaljohann-2denker commented on packages/apptive_grid_core/lib/src/model/s_view/s_view.dart
> -      fieldProperties: fieldProperties,
I changed it so both versions can be passed and added some tests for it

2023-11-08 13:42 UTC, ABausG reviewed
Just some last nits:

- Maybe move the migration test responses to separate files so the test file itself is a bit more readable
- I guess this is now rather a feature than a refactor. Also make sure that the spelling of the title is correct before merging and fits better as a changelog message something like: `Support slots for SViews`

2023-11-08 13:54 UTC, soeren-schmaljohann-2denker commented
> Just some last nits:
> 
> * Maybe move the migration test responses to separate files so the test file itself is a bit more readable
> * I guess this is now rather a feature than a refactor. Also make sure that the spelling of the title is correct before merging and fits better as a changelog message something like: `Support slots for SViews`

@ABausG done

2023-11-08 15:31 UTC, ABausG approved these changes

2023-11-08 16:46 UTC, merged